name: Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    container:
      image: nvcr.io/nvidia/pytorch:25.03-py3
      options: --gpus all

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run benchmark
      run: |
        python src/main.py \
          --model facebook/opt-6.7b \
          --backend both \
          --batch-sizes 1 2 \
          --precisions fp16

    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: |
          results/*.yaml
          results/plots/*.png 