name: Self-Hosted GPU Runner

on:
  workflow_dispatch:
    inputs:
      model:
        description: 'Model to benchmark'
        required: true
        default: 'facebook/opt-6.7b'
      backend:
        description: 'Backend to use'
        required: true
        default: 'pytorch'
        type: choice
        options:
          - pytorch
          - tensorrt
          - both

jobs:
  benchmark:
    runs-on: self-hosted
    container:
      image: nvcr.io/nvidia/pytorch:24.03-py3
      options: --gpus all

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run benchmark
      run: |
        python src/main.py \
          --model ${{ github.event.inputs.model || 'facebook/opt-6.7b' }} \
          --backend ${{ github.event.inputs.backend || 'pytorch' }} \
          --output-dir results

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: results/
        retention-days: 5

    - name: Generate report
      run: |
        python scripts/generate_report.py --input-dir results --output-dir reports

    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-report
        path: reports/
        retention-days: 5 